### ISSUE TITLE
Gather Data

### ISSUE THREAD

**Issue by pablomdd** [MLH-Fellowship/FreeCourseX#1]
- [ ] Coursera
- [ ] YouTube
- [ ] Free Code Camp

**Comment by gprmarquez** [comment]
**Progress**: 
 --
- [x] Coursera scraper draft finished
- [x] Medium scraper draft finished

**Notes**:
- Currently pointed at a search result page (Ex. "https://www.coursera.org/search?query=scraping&"), but once the front end is drafted, the scraper will run based on user input
- The results are added to the appropriate rows within the CSV

**To-Do**:
- [ ] Scrapers need to be converted to functions that can be called
- [ ] Need to add "if none" functionality in the event the element does not exist at all or for a specific iteration
- [ ] Find out how to add rows continuously instead of overwriting when adding to the CSV
